Feature/183959488 pixi update
SpringRoll/Springroll-Seed pull request #72
Opened 2022-12-09 20:30 UTC by 902seanryan

2022-12-09 21:47 UTC, deycorinne requested changes
One small thing

2022-12-09 21:47 UTC, deycorinne commented on webpack.config.js
> +    // entry: ['@babel/polyfill', path.join(__dirname, '/src/index.js')],
can this be removed?

2022-12-12 15:26 UTC, deycorinne approved these changes

2022-12-12 15:45 UTC, selenaqian approved these changes

2022-12-12 16:59 UTC, jeremymccurdy-redspace approved these changes

2022-12-13 12:48 UTC, jeremymccurdy-redspace approved these changes

2022-12-13 18:49 UTC, TensAndTwenties approved these changes

2022-12-21 17:32 UTC, merged